# Alpha is a float and can take value from 0.0 to 1.0
# All colors here can be either just "#FFFFFF" or { hex: "#FFFFFF", alpha:1.0 }
# If alpha is not specified, it is considered 1.0.
[general]
framerate = 60
background_color = { hex = "#000000", alpha = 0.0 }
# autosens = true
# sensitivity = 100
# Optionally you can set your monitor name, if your are on hyprland you can get it using `hyprctl monitors all`
# preferred_output = ""

[bars]
amount = 76
# `gap` is part of the actual bar width, so if `gap` is 0.1 then the gap width is 10% of the bar width.
gap = 0.1

[colors]
# These parameters can be named however you like, only the values matter here.
gradient_color_1 = '#94e2d5'
gradient_color_2 = '#89dceb'
gradient_color_3 = '#74c7ec'
gradient_color_4 = '#89b4fa'
gradient_color_5 = '#cba6f7'
gradient_color_6 = '#f5c2e7'
gradient_color_7 = '#eba0ac'
gradient_color_8 = '#f38ba8'

[smoothing]
# Smoothing just passes these parameters to cava, so description is also copied(I didn't add support to deprecated options)

# Disables or enables the so-called "Monstercat smoothing" with or without "waves". Set to 0 to disable.
# monstercat = 0
# At the time of writing this line of code, waves work properly in raw mode(which wallpaper-cava relies on) only if you compile cava from github.
# waves = 0

# Noise reduction, float 0 - 1. default 0.77
# the raw visualization is very noisy, this factor adjusts the integral and gravity filters to keep the signal smooth
# 1 will be very slow and smooth, 0 will be fast but noisy.
# noise_reduction = 0.77
